import io
from fpdf import FPDF, XPos, YPos


# Colour constants (RGB tuples for set_text_color / set_fill_color)
NEON_GREEN  = (0, 200, 65)
DARK_BG     = (14, 17, 23)
WHITE       = (255, 255, 255)
LIGHT_GRAY  = (240, 240, 240)
MID_GRAY    = (150, 150, 150)
RED         = (220, 50, 50)
ORANGE      = (220, 130, 0)
YELLOW      = (180, 140, 0)

GRADE_COLORS = {
    "A+": NEON_GREEN,
    "A":  (50, 190, 50),
    "B":  (180, 140, 0),
    "C":  (220, 130, 0),
    "D":  (220, 80, 0),
    "F":  (220, 50, 50),
}

FOOTER_TEXT = (
    "Generated by BiasMap AI v3.0  |  DPDP Compliance Audit  |  Local-Only Execution"
)


# Unicode → ASCII sanitiser

_UNICODE_MAP = {
    "\u2014": "-",    # em dash  —
    "\u2013": "-",    # en dash  –
    "\u2019": "'",    # right single quote  '
    "\u2018": "'",    # left single quote  '
    "\u201c": '"',    # left double quote  "
    "\u201d": '"',    # right double quote  "
    "\u2026": "...",  # ellipsis  …
    "\u00d7": "x",    # multiplication sign  ×
    "\u2713": "[OK]", # checkmark  ✓
    "\u2714": "[OK]", # heavy checkmark  ✔
    "\u26a0": "[!]",  # warning sign  ⚠
    "\u2248": "~",    # approximately equal  ≈
    "\u2264": "<=",   # less-than-or-equal  ≤
    "\u2265": ">=",   # greater-than-or-equal  ≥
    "\u00b1": "+/-",  # plus-minus  ±
}

def _safe(text: str) -> str:

    if not isinstance(text, str):
        text = str(text)
    # Replace known mappings first
    for uni, asc in _UNICODE_MAP.items():
        text = text.replace(uni, asc)
    # Drop anything still outside Latin-1 range (0x00–0xFF), e.g. emoji
    return text.encode("latin-1", errors="ignore").decode("latin-1")


# Custom FPDF subclass

class BiasMapPDF(FPDF):

    def header(self):
        # Black header bar spanning full page width
        self.set_fill_color(*DARK_BG)
        self.rect(0, 0, 210, 18, style="F")

        # Title text in neon green
        self.set_font("Courier", "B", 12)
        self.set_text_color(*NEON_GREEN)
        self.set_xy(10, 4)
        self.cell(
            0, 10,
            _safe("BiasMap AI -- Data Nutrition Label"),
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
        # Reset text colour for body content
        self.set_text_color(0, 0, 0)
        self.ln(6)

    def footer(self):
        self.set_y(-12)
        self.set_font("Courier", "I", 7)
        self.set_text_color(*MID_GRAY)
        self.cell(0, 10, _safe(FOOTER_TEXT), align="C")

    # Reusable layout helpers

    def section_title(self, text: str):

        self.ln(4)
        self.set_font("Courier", "B", 11)
        self.set_text_color(*NEON_GREEN)
        self.cell(0, 8, _safe(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        # Thin neon underline
        self.set_draw_color(*NEON_GREEN)
        self.set_line_width(0.4)
        self.line(10, self.get_y(), 200, self.get_y())
        self.set_text_color(0, 0, 0)
        self.set_draw_color(0, 0, 0)
        self.ln(3)

    def body_text(self, text: str, size: int = 9):

        self.set_font("Courier", "", size)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 5, _safe(text))
        self.ln(2)

    def kv_row(self, key: str, value: str, value_color=None):

        self.set_font("Courier", "B", 9)
        self.set_text_color(*MID_GRAY)
        self.cell(62, 6, _safe(key), new_x=XPos.RIGHT, new_y=YPos.TOP)

        self.set_font("Courier", "", 9)
        self.set_text_color(*(value_color or (40, 40, 40)))
        self.cell(0, 6, _safe(value), new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0, 0, 0)

    def table_header(self, cols: list):

        self.set_font("Courier", "B", 8)
        self.set_fill_color(*DARK_BG)
        self.set_text_color(*NEON_GREEN)
        for label, w in cols:
            self.cell(w, 7, _safe(label), border=1, fill=True, align="C")
        self.ln()
        self.set_text_color(0, 0, 0)

    def table_row(self, cells: list, fill: bool = False, text_color=None):

        self.set_font("Courier", "", 8)
        self.set_fill_color(*(LIGHT_GRAY if fill else WHITE))
        self.set_text_color(*(text_color or (40, 40, 40)))
        for text, w in cells:
            # Truncate at 42 chars so text never overflows its cell
            self.cell(w, 6, _safe(str(text))[:42], border=1, fill=True)
        self.ln()
        self.set_text_color(0, 0, 0)


# Public API 

def generate_pdf_report(
    dataset_name: str,
    row_count: int,
    col_count: int,
    sensitive_cols: list,
    compliance_result: dict,          # from compute_compliance_grade()
    entropy_scores: dict,             # {col_name: entropy_bits}
    kl_score: float,
    deserts: list,                    # from detect_representation_deserts()
    ghost_bias: dict,                 # {col: gini_importance} sorted desc
    fix_applied: bool = False,
    fix_method: str = None,
    entropy_before: float = None,
    entropy_after: float = None,
) -> bytes:


    pdf = BiasMapPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.set_margins(10, 22, 10)   # left=10, top=22 (clears header bar), right=10


    # PAGE 1 — EXECUTIVE SUMMARY

    pdf.add_page()

    pdf.section_title("1.  DATASET OVERVIEW")
    pdf.kv_row("Dataset Name  :", dataset_name)
    pdf.kv_row("Total Rows    :", f"{row_count:,}")
    pdf.kv_row("Total Columns :", str(col_count))
    pdf.kv_row(
        "Sensitive Cols:",
        ", ".join(sensitive_cols) if sensitive_cols else "None",
    )
    pdf.ln(4)

    # Compliance Grade 
    pdf.section_title("2.  DPDP / NITI AAYOG COMPLIANCE GRADE")

    grade       = compliance_result.get("grade", "?")
    badge_text  = compliance_result.get("badge_text", "")
    grade_color = GRADE_COLORS.get(grade, (100, 100, 100))

    # Large centred grade letter
    pdf.set_font("Courier", "B", 48)
    pdf.set_text_color(*grade_color)
    pdf.cell(0, 22, _safe(grade), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.set_font("Courier", "B", 12)
    pdf.cell(0, 8, _safe(badge_text), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(4)

    # KL Divergence headline
    pdf.set_font("Courier", "", 9)
    pdf.set_text_color(40, 40, 40)
    pdf.multi_cell(
        0, 5,
        _safe(
            f"KL Divergence Score (vs. Uniform Benchmark): {kl_score:.6f}"
            "   [0.0 = perfect equality  |  higher = more biased]"
        ),
    )
    pdf.ln(4)

    # Shannon Entropy table
    pdf.section_title("3.  SHANNON ENTROPY -- DIVERSITY METRICS")

    pdf.body_text(
        "Entropy measures how evenly a column's values are distributed. "
        "Higher = more diverse. Max = log2(unique categories).",
        size=8,
    )

    col_defs = [
        ("Sensitive Column", 95),
        ("Entropy (bits)",   50),
        ("% of Max Diversity", 45),
    ]
    pdf.table_header(col_defs)

    import math
    for i, (col, h_val) in enumerate(entropy_scores.items()):
        # Recompute % of max from the entropy value itself (safe approximation)
        # We don't have n_unique here, but a % label is still useful
        pct_label = "n/a"
        if h_val > 0:
            # We can't recalculate exact max without nunique, so label it as raw bits
            pct_label = f"{h_val:.4f} bits"

        cells = [
            (col,              95),
            (f"{h_val:.4f}",   50),
            (pct_label,        45),
        ]
        pdf.table_row(cells, fill=(i % 2 == 0))


    # PAGE 2 — BIAS FINDINGS

    pdf.add_page()

    # Representation Deserts
    pdf.section_title("4.  REPRESENTATION DESERTS  (top 5 worst intersections)")
    pdf.body_text(
        "Intersections with < 1% representation. "
        "These are the gaps that will bake discrimination into model weights.",
        size=8,
    )

    if not deserts:
        pdf.body_text(
            "[OK]  No representation deserts detected. "
            "All intersectional combinations have >= 1% representation."
        )
    else:
        desert_col_defs = [
            ("Intersection",  105),
            ("Count",          20),
            ("% Dataset",      30),
            ("Severity",       35),
        ]
        pdf.table_header(desert_col_defs)

        for i, d in enumerate(deserts[:5]):
            raw_sev = d.get("severity", "")
            # Strip emoji — _safe() will drop them anyway, but be explicit
            clean_sev = (
                raw_sev
                .replace("🔴", "").replace("🟠", "").replace("🟡", "")
                .strip()
            )

            # Row colour by severity
            if "ABSENT"   in raw_sev: row_color = RED
            elif "CRITICAL" in raw_sev: row_color = ORANGE
            else:                       row_color = YELLOW

            # Strip × from combination string too
            combo = d.get("combination", "").replace("×", "x")

            cells = [
                (combo,                             105),
                (str(d.get("count", 0)),             20),
                (f"{d.get('percentage', 0):.4f}%",   30),
                (clean_sev,                          35),
            ]
            pdf.table_row(cells, fill=(i % 2 == 0), text_color=row_color)

    pdf.ln(4)

    # Ghost Bias
    pdf.section_title("5.  GHOST BIAS ANALYSIS  (top 3 proxy features)")
    pdf.body_text(
        "A shallow Decision Tree (max_depth=4) trained on sensitive columns "
        "reveals which column best predicts the target -- i.e. the strongest proxy bias.",
        size=8,
    )

    if not ghost_bias:
        pdf.body_text(
            "Ghost Bias simulation was not run "
            "(no Target column was selected in the Schema screen)."
        )
    else:
        gb_col_defs = [("Column / Feature", 125), ("Gini Importance Score", 65)]
        pdf.table_header(gb_col_defs)

        for i, (col, score) in enumerate(list(ghost_bias.items())[:3]):
            cells = [(col, 125), (f"{score:.6f}", 65)]
            pdf.table_row(cells, fill=(i % 2 == 0))

        top_col   = list(ghost_bias.keys())[0]
        top_score = list(ghost_bias.values())[0]
        pdf.ln(3)
        pdf.set_font("Courier", "B", 9)
        pdf.set_text_color(*RED)
        pdf.multi_cell(
            0, 5,
            _safe(
                f"[!] Highest proxy bias: '{top_col}' "
                f"(Gini Importance = {top_score:.4f}). "
                "This column may act as a proxy for a protected attribute "
                "and should be reviewed before model deployment."
            ),
        )
        pdf.set_text_color(0, 0, 0)

    pdf.ln(4)

    # Legal Risk Summary
    pdf.section_title("6.  LEGAL RISK SUMMARY")
    pdf.body_text(compliance_result.get("risk_summary", "N/A"), size=9)


    # PAGE 3 — MITIGATION & RECOMMENDATIONS

    pdf.add_page()

    pdf.section_title("7.  AUTO-FIX / MITIGATION APPLIED")

    pdf.kv_row("Fix Applied :", "YES" if fix_applied else "NO")

    if fix_applied and fix_method:
        pdf.kv_row("Method Used :", fix_method)

        if entropy_before is not None:
            pdf.kv_row("Entropy Before:", f"{entropy_before:.4f} bits")
        if entropy_after is not None:
            pdf.kv_row("Entropy After :", f"{entropy_after:.4f} bits")

        if entropy_before and entropy_after and entropy_before > 0:
            gain = ((entropy_after - entropy_before) / entropy_before) * 100
            gain_color = NEON_GREEN if gain >= 0 else RED
            pdf.set_font("Courier", "B", 9)
            pdf.set_text_color(*gain_color)
            pdf.cell(
                0, 6,
                _safe(f"    Entropy Gain : {gain:+.2f}%"),
                new_x=XPos.LMARGIN, new_y=YPos.NEXT,
            )
            pdf.set_text_color(0, 0, 0)
    else:
        pdf.ln(2)
        pdf.body_text(
            "No mitigation was applied during this audit session. "
            "See recommendations below for next steps."
        )

    pdf.ln(4)

    # Grade-based recommendations
    pdf.section_title("8.  RECOMMENDATIONS")

    recs = {
        "A+": (
            "Your dataset demonstrates excellent representational balance. "
            "No immediate remediation is required. Conduct periodic re-audits "
            "as new data is ingested to maintain compliance with DPDP "
            "'Fair Processing' norms. Document this audit result as evidence "
            "of due diligence for regulatory submissions."
        ),
        "A": (
            "Minor distributional drift detected. The dataset is generally "
            "compliant. Consider light augmentation for any under-represented "
            "sub-groups identified in the Deserts section. Re-audit after "
            "each major data refresh cycle."
        ),
        "B": (
            "Moderate bias detected. Run the Auto-Fix engine (SMOTE or "
            "Under-sampling) before initiating model training. Disclose "
            "dataset limitations in model cards per DPDP and NITI Aayog "
            "responsible AI guidelines. Target an entropy gain of at least "
            "20% post-remediation before re-submitting for audit."
        ),
        "C": (
            "Elevated bias risk identified. Training on this dataset without "
            "remediation carries a HIGH likelihood of producing discriminatory "
            "model outputs. Apply SMOTE to minority classes, then re-audit. "
            "Engage a data ethics reviewer before any production deployment. "
            "Document all remediation steps for regulatory audit trails."
        ),
        "D": (
            "Severe distributional skew detected. This dataset is likely to "
            "produce models that violate DPDP 'Fair Processing' mandates. "
            "Mandatory remediation is required before any further use. "
            "Consider sourcing additional real data for under-represented "
            "groups rather than relying solely on synthetic augmentation. "
            "Legal review is strongly advised before deployment."
        ),
        "F": (
            "CRITICAL VIOLATION. This dataset is fundamentally "
            "unrepresentative and must NOT be used for model training "
            "without comprehensive remediation. Halt all training pipelines "
            "immediately. Engage legal counsel, re-source the underlying "
            "data, and conduct a full ethics review before resubmitting "
            "for audit. Proceeding with training may constitute a direct "
            "DPDP Act (2023) violation and expose your organisation to "
            "regulatory and civil liability."
        ),
    }

    rec_text = recs.get(grade, "Please consult a data ethics professional.")
    pdf.body_text(rec_text, size=9)

    # Return as bytes
    return bytes(pdf.output())